# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# See https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles

logger: pypsa

prioritize:
- solve_sector_network_myopic
- solve_sector_network_myopic_mga
