# SPDX-FileCopyrightText: Peter Kröning and Contributors to <https://github.com/koen-vg/eu-hydrogen>
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "myopic-mga"
  default_target_rule: "plot_all_summaries"

foresight: myopic

scenario:
  planning_horizons:
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050
  mga:
    slack:
    - 0.02
    - 0.05
    - 0.1
    slack_initial_fraction: 0.5
    alternative_objectives:
      # Technology focus
      min-tech_H2_El:
        weights:
          varying:
            Link:
              p:
                "H2 Electrolysis": 1
      max-tech_H2_El:
        weights:
          varying:
            Link:
              p:
                "H2 Electrolysis": 1

      # Autarky
      min-imports_elec:
        weights:
          varying:
            Link:
              p:
                "DC": 1
            Line:
              s:  # TODO
                "AC": 1
    region:
    - DE
